export * from './validarCalle'
export * from './validarColonia'
export * from './validarNumeroExt'
export * from './validarCP'
export * from './cambiarEstado'
export * from './validarFormulario'
export * from './coloresInputs'
